enum Build {
  NONE
  CLIENT
  SERVER
}

const BUILD Build = .NONE
const PROFILE = false

@skip if !RELEASE && PROFILE
def assert(truth bool)

@import {
  const console dynamic
  const window dynamic
  const document dynamic
  const THREE dynamic
  const WebSocket dynamic
  const location dynamic

  def setTimeout(callback fn(), milliseconds int) int
  def clearTimeout(interval int)

  def setInterval(callback fn(), milliseconds int) int
  def clearInterval(interval int)
}
