class AABB {
  var center = THREE.Vector3.new()
  var radius = THREE.Vector3.new()
}

class World {
  const scene dynamic
  const _terrain Terrain
  const clearColor = THREE.Color.new(0x7FBFFF)

  def new(scene dynamic) {
    self.scene = scene
    _terrain = Terrain.new(self)
  }

  def moveAABB(aabb AABB, delta dynamic) {
    _terrain.moveAABB(aabb, delta)
  }

  def tick(camera dynamic) {
    _terrain.tick(camera)
  }
}
