class AABB {
  var center = THREE.Vector3.new()
  var radius = THREE.Vector3.new()
}

class World {
  const _scene dynamic
  const _terrain Terrain

  def new(scene dynamic) {
    _scene = scene
    _terrain = Terrain.new(self)
  }

  def moveAABB(aabb AABB, delta dynamic) {
    _terrain.moveAABB(aabb, delta)
  }

  def scene dynamic {
    return _scene
  }

  def tick(camera dynamic) {
    _terrain.tick(camera)
  }
}

namespace World {
  const CLEAR_COLOR = THREE.Color.new(0x7FBFFF)
}
